export const initialState = {
  posts: {
    data: [
      {
        id: '1ab',
        title: 'Buletin 1',
        content: 'Nulla ac turpis rutrum pede sit amet sapien eu odio. Morbi a blandit quam eros ac turpis egestas. Suspendisse ac quam in dictum eget, elementum nunc. Nulla venenatis arcu',
        datePublication: '2021.03.12',
        dateLastUpdate: '2021.03.27',
        email: 'john@lorem.com',
        status: 'published',
        image: 'https://images.pexels.com/photos/8418292/pexels-photo-8418292.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        price: '100',
        phone: '123456789',
        location: 'Londyn',
      },
      {
        id: 'ds2',
        title: 'Buletin 2',
        content: 'Nulla ac turpis rutrum pede sit amet sapien eu odio. Morbi a blandit quam eros ac turpis egestas. Suspendisse ac quam in dictum eget, elementum nunc. Nulla venenatis arcu',
        datePublication: '2021.02.23',
        dateLastUpdate: '2021.04.11',
        email: 'donald@lorem.com',
        status: 'draft',
        image: 'https://images.pexels.com/photos/4353813/pexels-photo-4353813.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        price: '150',
        phone: '987654321',
        location: 'Katowice',
      },
      {
        id: 'bl3',
        title: 'Buletin 3',
        content: 'Nulla ac turpis rutrum pede sit amet sapien eu odio. Morbi a blandit quam eros ac turpis egestas. Suspendisse ac quam in dictum eget, elementum nunc. Nulla venenatis arcu',
        datePublication: '2021.01.29',
        dateLastUpdate: '2021.01.29',
        email: 'jeremy@lorem.com',
        status: 'draft',
        image: 'https://images.pexels.com/photos/8412193/pexels-photo-8412193.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        price: '120',
        phone: '111222333',
        location: 'Radom',
      },
      {
        id: 'hl4',
        title: 'Buletin 4',
        content: 'Nulla ac turpis rutrum pede sit amet sapien eu odio. Morbi a blandit quam eros ac turpis egestas. Suspendisse ac quam in dictum eget, elementum nunc. Nulla venenatis arcu',
        datePublication: '2021.01.23',
        dateLastUpdate: '2021.04.15',
        email: 'manuela@lorem.com',
        status: 'published',
        image: 'https://images.pexels.com/photos/8369440/pexels-photo-8369440.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        price: '88',
        phone: '432543654',
        location: 'Warszawa',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
};
